CREATE TABLE MEMBER(         
M_INDEX   NUMBER(6)      ,
M_ID   VARCHAR2(50)   NOT NULL   ,
M_PASSWORD   VARCHAR2(50)   NOT NULL   ,
M_NAME   VARCHAR2(100)   NOT NULL   ,
M_TEL   VARCHAR2(100)   NOT NULL   ,
M_EMAIL   VARCHAR2(100)   NOT NULL   ,
M_ADDRESS   VARCHAR2(100)   NOT NULL   ,
M_ADDRESS_SEC   VARCHAR2(100)   NOT NULL   ,
M_BIRTH   DATE   NOT NULL   ,
M_SIGN_TIME   DATE   DEFAULT SYSDATE   ,
M_POINT   NUMBER(9)   DEFAULT 0   ,
M_NOTE   VARCHAR2(4000)      
);      




CREATE TABLE MEMBER(         
M_INDEX   NUMBER(6)      ,
M_ID   VARCHAR2(50)   NOT NULL   ,
M_PASSWORD   VARCHAR2(50)   NOT NULL   ,
M_NAME   VARCHAR2(100)   NOT NULL   ,
M_TEL   VARCHAR2(100)   NOT NULL   ,
M_EMAIL   VARCHAR2(100)   NOT NULL   ,
M_ADDRESS   VARCHAR2(100)   NOT NULL   ,
M_ADDRESS_SEC   VARCHAR2(100)   NOT NULL   ,
M_BIRTH   DATE   NOT NULL   ,
M_SIGN_TIME   DATE   DEFAULT SYSDATE   ,
M_POINT   NUMBER(9)   DEFAULT 0   ,
M_NOTE   VARCHAR2(4000)      
);      

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_M_INDEX_PK PRIMARY KEY(M_INDEX)
ADD CONSTRAINT MEMBER_M_ID_UK UNIQUE (M_ID)
ADD CONSTRAINT MEMBER_M_EMAIL_UK UNIQUE (M_EMAIL);


CREATE TABLE PRODUCT(
P_INDEX   NUMBER(6),
P_NAME   VARCHAR2(100)   NOT NULL,
P_PRICE   NUMBER(6)   NOT NULL,
P_STOCK   NUMBER(6)   DEFAULT 0,
P_INTRO   CLOB   ,
P_OPEN   NUMBER(1,0)   DEFAULT 0,
P_IMAGE   VARCHAR2(4000)   
);

ALTER TABLE PRODUCT
ADD CONSTRAINT PRODUCT_P_INDEX_PK PRIMARY KEY (P_INDEX);


CREATE TABLE DESSERT(
D_INDEX   NUMBER(6)   ,
D_NAME   VARCHAR2(255)   NOT NULL,
D_TEXT   CLOB   ,
D_IMAGE   VARCHAR2(4000),
D_VIEW   NUMBER(6),   
D_OPEN   NUMBER(1,0)   DEFAULT 0
);

ALTER TABLE DESSERT
ADD CONSTRAINT DESSERT_D_INDEX_PK PRIMARY KEY (D_INDEX);

CREATE TABLE FREE_BOARD(
F_index   NUMBER(6)   ,
M_ID   VARCHAR2(50),
F_SUBJECT   VARCHAR2(255)   ,
F_TEXT   CLOB   ,
F_IMAGE   VARCHAR2(4000)   ,
F_CRE_DATE   DATE   DEFAULT SYSDATE,
F_VIEW NUMBER(6),
F_NOTICE   NUMBER(1,0)   DEFAULT 0
);


ALTER TABLE FREE_BOARD
ADD CONSTRAINT FREEBOARD_F_INDEX_PK PRIMARY KEY (F_INDEX)
ADD CONSTRAINT FREEBOARD_M_ID_FK FOREIGN KEY(M_ID) REFERENCES MEMBER(M_ID);



CREATE TABLE REPLY(
R_INDEX   NUMBER(6),
M_ID   VARCHAR2(50),
R_TEXT   VARCHAR2(4000)   ,
F_INDEX   NUMBER(6)   ,
R_CRE_DATE   DATE   DEFAULT SYSDATE
);

ALTER TABLE REPLY
ADD CONSTRAINT REPLY_R_INDEX_PK PRIMARY KEY(R_INDEX)
ADD CONSTRAINT REPLY_M_ID_FK FOREIGN KEY (M_ID) REFERENCES MEMBER (M_ID)
ADD CONSTRAINT REPLY_F_INDEX_FK FOREIGN KEY (F_INDEX) REFERENCES FREE_BOARD (F_INDEX) ON DELETE CASCADE;

CREATE TABLE TAG(
T_INDEX   NUMBER(6),
T_NAME   VARCHAR2(20)NOT NULL
);

ALTER TABLE TAG
ADD CONSTRAINT TAG_T_INDEX_PK PRIMARY KEY (T_INDEX)
ADD CONSTRAINT TAG_T_NAME_UK UNIQUE (T_NAME);

CREATE TABLE BASKET(
M_INDEX   NUMBER(6),
P_INDEX   NUMBER(6),
B_STOCK   NUMBER(2),
B_CRE_DATE DATE DEFAULT SYSDATE
);


ALTER TABLE BASKET
ADD CONSTRAINT BASKET_M_INDEX_FK FOREIGN KEY (M_INDEX) REFERENCES MEMBER(M_INDEX) ON DELETE CASCADE
ADD CONSTRAINT BASKET_P_INDEX_FK FOREIGN KEY (P_INDEX) REFERENCES PRODUCT(P_INDEX) ON DELETE CASCADE;


CREATE TABLE PRODUCT_TAG(
P_INDEX   NUMBER(6),
T_INDEX   NUMBER(6)
);

ALTER TABLE PRODUCT_TAG
ADD CONSTRAINT PT_P_INDEX_FK FOREIGN KEY(P_INDEX) REFERENCES PRODUCT (P_INDEX)
ADD CONSTRAINT PT_T_INDEX_FK FOREIGN KEY(T_INDEX) REFERENCES TAG (T_INDEX);



CREATE TABLE STATUS(
STA_INDEX   NUMBER(2),
STA_STATUS   VARCHAR2(255) NOT NULL,
STA_NOTICE   VARCHAR2(255) NOT NULL
);

ALTER TABLE STATUS
ADD CONSTRAINT STATUS_STA_INDEX_PK PRIMARY KEY (STA_INDEX)
ADD CONSTRAINT STATUS_STA_STATUS_UK UNIQUE (STA_STATUS)
ADD CONSTRAINT STATUS_STA_NOTICE_UK UNIQUE (STA_NOTICE);

CREATE TABLE DESSERT_TAG(
D_INDEX   NUMBER(6),
T_INDEX   NUMBER(6)
);

ALTER TABLE DESSERT_TAG
ADD CONSTRAINT DT_D_INDEX_FK FOREIGN KEY (D_INDEX) REFERENCES DESSERT (D_INDEX)
ADD CONSTRAINT DT_T_INDEX_FK FOREIGN KEY (T_INDEX) REFERENCES TAG (T_INDEX);

CREATE TABLE MEMBER_ORDER(
O_INDEX   NUMBER(6),
M_INDEX   NUMBER(6)
);



CREATE TABLE S_ORDER(
O_INDEX   NUMBER(6),
STA_STATUS   VARCHAR2(20),
O_TIME   DATE   DEFAULT SYSDATE,
M_ADDRESS   VARCHAR2(100)   ,
M_ADDRESS_SEC   VARCHAR2(100)   ,
M_TEL   VARCHAR2(100)   
);

ALTER TABLE S_ORDER
ADD CONSTRAINT SO_O_INDEX PRIMARY KEY(O_INDEX)
ADD CONSTRAINT SO_STA_STATUS FOREIGN KEY(STA_STATUS) REFERENCES STATUS(STA_STATUS);

ALTER TABLE MEMBER_ORDER
ADD CONSTRAINT MO_O_INDEX FOREIGN KEY (O_INDEX) REFERENCES S_ORDER (O_INDEX)
ADD CONSTRAINT MO_M_INDEX FOREIGN KEY (M_INDEX) REFERENCES MEMBER (M_INDEX);



ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_M_INDEX_PK PRIMARY KEY(M_INDEX)
ADD CONSTRAINT MEMBER_M_ID_UK UNIQUE (M_ID)
ADD CONSTRAINT MEMBER_M_EMAIL_UK UNIQUE (M_EMAIL);


CREATE TABLE PRODUCT(
P_INDEX   NUMBER(6),
P_NAME   VARCHAR2(100)   NOT NULL,
P_PRICE   NUMBER(6)   NOT NULL,
P_STOCK   NUMBER(6)   DEFAULT 0,
P_INTRO   CLOB   ,
P_OPEN   NUMBER(1,0)   DEFAULT 0,
P_IMAGE   VARCHAR2(4000)   
);

ALTER TABLE PRODUCT
ADD CONSTRAINT PRODUCT_P_INDEX_PK PRIMARY KEY (P_INDEX);


CREATE TABLE DESSERT(
D_INDEX   NUMBER(6)   ,
D_NAME   VARCHAR2(255)   NOT NULL,
D_TEXT   CLOB   ,
D_IMAGE   VARCHAR2(4000),
D_VIEW   NUMBER(6),   
D_OPEN   NUMBER(1,0)   DEFAULT 0
);

ALTER TABLE DESSERT
ADD CONSTRAINT DESSERT_D_INDEX_PK PRIMARY KEY (D_INDEX);

CREATE TABLE FREE_BOARD(
F_index   NUMBER(6)   ,
M_ID   VARCHAR2(50),
F_SUBJECT   VARCHAR2(255)   ,
F_TEXT   CLOB   ,
F_IMAGE   VARCHAR2(4000)   ,
F_CRE_DATE   DATE   DEFAULT SYSDATE,
F_VIEW NUMBER(6),
F_NOTICE   NUMBER(1,0)   DEFAULT 0
);


ALTER TABLE FREE_BOARD
ADD CONSTRAINT FREEBOARD_F_INDEX_PK PRIMARY KEY (F_INDEX)
ADD CONSTRAINT FREEBOARD_M_ID_FK FOREIGN KEY(M_ID) REFERENCES MEMBER(M_ID);



CREATE TABLE REPLY(
R_INDEX   NUMBER(6),
M_ID   VARCHAR2(50),
R_TEXT   VARCHAR2(4000)   ,
F_INDEX   NUMBER(6)   ,
R_CRE_DATE   DATE   DEFAULT SYSDATE
);

ALTER TABLE REPLY
ADD CONSTRAINT REPLY_R_INDEX_PK PRIMARY KEY(R_INDEX)
ADD CONSTRAINT REPLY_M_ID_FK FOREIGN KEY (M_ID) REFERENCES MEMBER (M_ID)
ADD CONSTRAINT REPLY_F_INDEX_FK FOREIGN KEY (F_INDEX) REFERENCES FREE_BOARD (F_INDEX) ON DELETE CASCADE;

CREATE TABLE TAG(
T_INDEX   NUMBER(6),
T_NAME   VARCHAR2(20)NOT NULL
);

ALTER TABLE TAG
ADD CONSTRAINT TAG_T_INDEX_PK PRIMARY KEY (T_INDEX)
ADD CONSTRAINT TAG_T_NAME_UK UNIQUE (T_NAME);

CREATE TABLE BASKET(
M_INDEX   NUMBER(6),
P_INDEX   NUMBER(6),
B_STOCK   NUMBER(2)
<<<<<<< HEAD
);

ALTER TABLE BASKET
ADD CONSTRAINT BASKET_M_INDEX_FK FOREIGN KEY (M_INDEX) REFERENCES MEMBER(M_INDEX)
ADD CONSTRAINT BASKET_P_INDEX_FK FOREIGN KEY (P_INDEX) REFERENCES PRODUCT(P_INDEX);
=======
B_CRE_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE BASKET
ADD CONSTRAINT BASKET_M_INDEX_FK FOREIGN KEY (M_INDEX) REFERENCES MEMBER(M_INDEX) ON DELETE CASCADE
ADD CONSTRAINT BASKET_P_INDEX_FK FOREIGN KEY (P_INDEX) REFERENCES PRODUCT(P_INDEX) ON DELETE CASCADE;
>>>>>>> branch 'main' of https://github.com/Chan242/K_dessert.git

CREATE TABLE PRODUCT_TAG(
P_INDEX   NUMBER(6),
T_INDEX   NUMBER(6)
);

ALTER TABLE PRODUCT_TAG
ADD CONSTRAINT PT_P_INDEX_FK FOREIGN KEY(P_INDEX) REFERENCES PRODUCT (P_INDEX)
ADD CONSTRAINT PT_T_INDEX_FK FOREIGN KEY(T_INDEX) REFERENCES TAG (T_INDEX);



CREATE TABLE STATUS(
STA_INDEX   NUMBER(2),
STA_STATUS   VARCHAR2(255) NOT NULL,
STA_NOTICE   VARCHAR2(255) NOT NULL
);

ALTER TABLE STATUS
ADD CONSTRAINT STATUS_STA_INDEX_PK PRIMARY KEY (STA_INDEX)
ADD CONSTRAINT STATUS_STA_STATUS_UK UNIQUE (STA_STATUS)
ADD CONSTRAINT STATUS_STA_NOTICE_UK UNIQUE (STA_NOTICE);

CREATE TABLE DESSERT_TAG(
D_INDEX   NUMBER(6),
T_INDEX   NUMBER(6)
);

ALTER TABLE DESSERT_TAG
ADD CONSTRAINT DT_D_INDEX_FK FOREIGN KEY (D_INDEX) REFERENCES DESSERT (D_INDEX)
ADD CONSTRAINT DT_T_INDEX_FK FOREIGN KEY (T_INDEX) REFERENCES TAG (T_INDEX);

CREATE TABLE MEMBER_ORDER(
O_INDEX   NUMBER(6),
M_INDEX   NUMBER(6)
);



CREATE TABLE S_ORDER(
O_INDEX   NUMBER(6),
STA_STATUS   VARCHAR2(20),
O_TIME   DATE   DEFAULT SYSDATE,
M_ADDRESS   VARCHAR2(100)   ,
M_ADDRESS_SEC   VARCHAR2(100)   ,
M_TEL   VARCHAR2(100)   
);

ALTER TABLE S_ORDER
ADD CONSTRAINT SO_O_INDEX PRIMARY KEY(O_INDEX)
ADD CONSTRAINT SO_STA_STATUS FOREIGN KEY(STA_STATUS) REFERENCES STATUS(STA_STATUS);

ALTER TABLE MEMBER_ORDER
ADD CONSTRAINT MO_O_INDEX FOREIGN KEY (O_INDEX) REFERENCES S_ORDER (O_INDEX)
ADD CONSTRAINT MO_M_INDEX FOREIGN KEY (M_INDEX) REFERENCES MEMBER (M_INDEX);


